{{- if .Values.marble.externalSecret.enabled }}
apiVersion: {{ include "marble.externalSecretApiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "marble.secretName" . }}
  namespace: {{ include "marble.namespace" . }}
  labels:
    {{- include "marble.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: {{ .Values.marble.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.marble.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "marble.secretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.marble.externalSecret.remoteSecretName }}
{{- if .Values.marble.externalSecret.jwtSigningKeyProperty }}
---
apiVersion: {{ include "marble.externalSecretApiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "marble.secretName" . }}-jwt
  namespace: {{ include "marble.namespace" . }}
  labels:
    {{- include "marble.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: {{ .Values.marble.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.marble.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "marble.secretName" . }}-jwt
    creationPolicy: Owner
  data:
    - secretKey: jwt.pem
      remoteRef:
        key: {{ .Values.marble.externalSecret.remoteSecretName }}
        property: {{ .Values.marble.externalSecret.jwtSigningKeyProperty }}
        decodingStrategy: Base64
{{- end }}
{{- if .Values.marble.firebase.gcpServiceAccountProperty }}
---
apiVersion: {{ include "marble.externalSecretApiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "marble.fullname" . }}-firebase-sa
  namespace: {{ include "marble.namespace" . }}
  labels:
    {{- include "marble.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: {{ .Values.marble.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.marble.externalSecret.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "marble.fullname" . }}-firebase-sa
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.marble.firebase.credentialsKey }}
      remoteRef:
        key: {{ .Values.marble.externalSecret.remoteSecretName }}
        property: {{ .Values.marble.firebase.gcpServiceAccountProperty }}
        decodingStrategy: Base64
{{- end }}
{{- end }}
