apiVersion: v1
kind: Service
metadata:
  name: {{ include "marble.fullname" . }}-frontend
  namespace: {{ include "marble.namespace" . }}
  labels:
    {{- include "marble.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "marble.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
